//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.v0._04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string IdClass { get; set; }
        public string IdStdTitle { get; set; }
        public string IdDept { get; set; }
        public string IdSubject { get; set; }
        public int TaughtYear { get; set; }
        public int Semester { get; set; }
        public string ClsLetter { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual StdTitle StdTitle { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
