//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.v0._04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public string IdEnrollment { get; set; }
        public string IdSubject { get; set; }
        public string IdStudent { get; set; }
        public int TaughtYear { get; set; }
        public int TaughtSemester { get; set; }
        public float GradePoint { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
