-- MySQL Script generated by MySQL Workbench
-- Wed Jan  2 10:35:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stmgt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stmgt` ;

-- -----------------------------------------------------
-- Schema stmgt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stmgt` DEFAULT CHARACTER SET utf8 ;
USE `stmgt` ;

-- -----------------------------------------------------
-- Table `stmgt`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stmgt`.`Departments` ;

CREATE TABLE IF NOT EXISTS `stmgt`.`Departments` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stmgt`.`Genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stmgt`.`Genders` ;

CREATE TABLE IF NOT EXISTS `stmgt`.`Genders` (
  `idGender` INT NOT NULL AUTO_INCREMENT,
  `Sex` VARCHAR(45) NULL,
  PRIMARY KEY (`idGender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stmgt`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stmgt`.`Students` ;

CREATE TABLE IF NOT EXISTS `stmgt`.`Students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `middleName` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `idDepartment` INT NOT NULL,
  `Genders_idGender` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `idDepartment`, `Genders_idGender`),
  INDEX `fk_Students_Departments_idx` (`idDepartment` ASC) VISIBLE,
  INDEX `fk_Students_Genders1_idx` (`Genders_idGender` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Departments`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `stmgt`.`Departments` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Genders1`
    FOREIGN KEY (`Genders_idGender`)
    REFERENCES `stmgt`.`Genders` (`idGender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stmgt`.`TheUniversity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stmgt`.`TheUniversity` ;

CREATE TABLE IF NOT EXISTS `stmgt`.`TheUniversity` (
  `Name` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
