-- MySQL Script generated by MySQL Workbench
-- Wed Jan  2 08:21:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `idDepartment` INT GENERATED ALWAYS AS () VIRTUAL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudent` INT GENERATED ALWAYS AS () VIRTUAL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `middleName` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `idDepartment` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `idDepartment`),
  INDEX `fk_Students_Departments_idx` (`idDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Departments`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `mydb`.`Departments` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TheUniversity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TheUniversity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TheUniversity` (
  `Name` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
