//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.v0._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int idClass { get; set; }
        public int idLecturer { get; set; }
        public int idSubject { get; set; }
        public int TaughtYear { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
