//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.v0._02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public int idClass { get; set; }
        public int idStudent { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<float> GradePoint { get; set; }
    }
}
