//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.v0._03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSeniority
    {
        public int idSeniority { get; set; }
        public string StudentTitle { get; set; }
        public int Years { get; set; }
    }
}
